import { CheckCircle2, Clock3, ShoppingCart, XCircle } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { getCurrentRole } from '@/lib/admin-auth'
import { SaleStatusActions } from '@/components/crm/sale-status-actions'

export const dynamic='force-dynamic'
type Sale={id:string;status:'pending'|'confirmed'|'cancelled';client_name:string;client_phone:string;product:string;total:string;note:string;sold_at:string;updated_at:string;agents:{code:string;users:{full_name:string}|null}|null;campaigns:{name:string}|null}
export default async function SalesPage(){
  const role=await getCurrentRole();const supabase=await createClient();let query=supabase.from('sales').select('id,status,client_name,client_phone,product,total,note,sold_at,updated_at,agents(code,users(full_name)),campaigns(name)').order('sold_at',{ascending:false}).limit(5000)
  if(role==='agent')query=query.gte('sold_at',new Date(Date.now()-3*24*60*60*1000).toISOString())
  const {data,error}=await query;const sales=(data??[]) as unknown as Sale[]
  const pending=sales.filter(sale=>sale.status==='pending').length;const confirmed=sales.filter(sale=>sale.status==='confirmed').length;const cancelled=sales.filter(sale=>sale.status==='cancelled').length
  const statusLabel={pending:'À confirmer',confirmed:'Confirmée',cancelled:'Annulée'};const statusClass={pending:'bg-amber-100 text-amber-800',confirmed:'bg-emerald-100 text-emerald-800',cancelled:'bg-red-100 text-red-700'}
  return <div className="space-y-6"><div><h1 className="flex items-center gap-3 text-2xl font-black"><ShoppingCart className="text-emerald-600"/>Ventes</h1><p className="mt-1 text-sm text-slate-500">{role==='agent'?'Vos ventes des trois derniers jours. Elles restent conservées dans la base après leur disparition de cette vue.':'Historique complet des ventes visibles selon votre rôle.'}</p></div><section className="grid gap-3 sm:grid-cols-3"><div className="card flex items-center gap-3 p-4"><Clock3 className="text-amber-600"/><div><p className="text-2xl font-black">{pending}</p><p className="text-xs text-slate-500">À confirmer</p></div></div><div className="card flex items-center gap-3 p-4"><CheckCircle2 className="text-emerald-600"/><div><p className="text-2xl font-black">{confirmed}</p><p className="text-xs text-slate-500">Confirmées</p></div></div><div className="card flex items-center gap-3 p-4"><XCircle className="text-red-500"/><div><p className="text-2xl font-black">{cancelled}</p><p className="text-xs text-slate-500">Annulées</p></div></div></section><section className="card overflow-x-auto"><div className="panel-title">Ventes triées de la plus récente à la plus ancienne</div>{error?<p className="p-6 text-sm font-bold text-red-600">Chargement impossible : {error.message}</p>:<table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-slate-50 uppercase text-slate-500"><tr><th className="p-3">Date et heure</th><th className="p-3">Agent</th><th className="p-3">Client</th><th className="p-3">Produit</th><th className="p-3">Total</th><th className="p-3">Campagne</th><th className="p-3">Statut</th><th className="p-3">Action</th></tr></thead><tbody>{sales.map(sale=><tr key={sale.id} className="border-t align-top hover:bg-slate-50"><td className="whitespace-nowrap p-3">{new Date(sale.sold_at).toLocaleString('fr-DZ')}</td><td className="p-3 font-bold">{sale.agents?.users?.full_name||sale.agents?.code||'Agent'}<p className="text-[10px] font-normal text-slate-400">{sale.agents?.code}</p></td><td className="p-3 font-bold">{sale.client_name}<p className="text-[10px] font-normal text-slate-500">{sale.client_phone}</p>{sale.note&&<p className="mt-1 max-w-64 text-[10px] font-normal text-slate-400">{sale.note}</p>}</td><td className="p-3">{sale.product||'—'}</td><td className="p-3 font-black">{sale.total||'—'}</td><td className="p-3">{sale.campaigns?.name||'—'}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusClass[sale.status]}`}>{statusLabel[sale.status]}</span></td><td className="p-3"><SaleStatusActions id={sale.id} current={sale.status}/></td></tr>)}{!sales.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">Aucune vente à afficher.</td></tr>}</tbody></table>}</section></div>
}
