import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getCurrentProfile } from '@/lib/admin-auth'
import { HelpManagement } from '@/components/crm/help-management'

export const dynamic='force-dynamic'
type VideoRow={id:string;title:string;description:string;storage_path:string;created_at:string}
export default async function HelpPage(){const profile=await getCurrentProfile();if(!profile)redirect('/login');const supabase=await createClient();if(profile.role==='admin'){const {data}=await supabase.from('users').select('id,full_name,email,role').in('role',['agent','supervisor']).order('full_name');return <div className="space-y-6"><div><h1 className="text-2xl font-black">Aide vidéo</h1><p className="mt-1 text-sm text-slate-500">Diffusez des consignes vidéo de manière ciblée.</p></div><HelpManagement recipients={(data??[]) as Parameters<typeof HelpManagement>[0]['recipients']}/></div>}const {data}=await supabase.from('help_videos').select('id,title,description,storage_path,created_at').order('created_at',{ascending:false});const rows=(data??[]) as VideoRow[];const admin=createAdminClient();const signed=await Promise.all(rows.map(async video=>({video,url:(await admin.storage.from('crm-help-videos').createSignedUrl(video.storage_path,3600)).data?.signedUrl||''})));return <div className="space-y-6"><div><h1 className="text-2xl font-black">Aide</h1><p className="mt-1 text-sm text-slate-500">Vidéos et consignes envoyées par l’administration.</p></div><div className="grid gap-5 lg:grid-cols-2">{signed.map(({video,url})=><article key={video.id} className="card overflow-hidden"><div className="aspect-video bg-slate-950">{url?<video controls preload="metadata" className="h-full w-full" src={url}/>:<p className="grid h-full place-items-center text-sm text-white">Vidéo indisponible</p>}</div><div className="p-5"><h2 className="font-black">{video.title}</h2>{video.description&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{video.description}</p>}<p className="mt-4 text-xs text-slate-400">Ajoutée le {new Date(video.created_at).toLocaleString('fr-DZ')}</p></div></article>)}{!signed.length&&<div className="card col-span-full p-10 text-center text-sm text-slate-500">Aucune vidéo d’aide ne vous a encore été attribuée.</div>}</div></div>}
