import Link from 'next/link'
import { ArrowLeft, CalendarClock, Coffee, PhoneCall, StickyNote } from 'lucide-react'
import { notFound, redirect } from 'next/navigation'
import { getCurrentRole } from '@/lib/admin-auth'
import { createClient } from '@/lib/supabase/server'

export const dynamic='force-dynamic'
type Call={id:string;called_at:string;duration_seconds:number;summary:string;clients:{first_name:string;last_name:string;phone:string}|null;call_results:{label:string;is_success:boolean;is_sale:boolean}|null;campaigns:{name:string}|null}
type Callback={id:string;scheduled_for:string;status:string;note:string;clients:{first_name:string;last_name:string}|null}
type Pause={id:string;pause_type:string;started_at:string;ended_at:string|null}
type Note={id:string;body:string;created_at:string;clients:{first_name:string;last_name:string}|null}
const formatSeconds=(total:number)=>`${String(Math.floor(total/3600)).padStart(2,'0')}:${String(Math.floor(total%3600/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`
export default async function AgentDetailPage({params}:{params:Promise<{id:string}>}){
  const role=await getCurrentRole();if(role!=='admin'&&role!=='supervisor')redirect('/dashboard')
  const {id}=await params;const supabase=await createClient()
  const {data:agent}=await supabase.from('agents').select('id,code,active,last_seen_at,users(full_name,email)').eq('id',id).maybeSingle();if(!agent)notFound()
  const [{data:callRows},{data:callbackRows},{data:pauseRows},{data:noteRows},{count:queueCount}]=await Promise.all([
    supabase.from('calls').select('id,called_at,duration_seconds,summary,clients(first_name,last_name,phone),call_results(label,is_success,is_sale),campaigns(name)').eq('agent_id',id).order('called_at',{ascending:false}).limit(500),
    supabase.from('callbacks').select('id,scheduled_for,status,note,clients(first_name,last_name)').eq('agent_id',id).order('scheduled_for',{ascending:false}).limit(300),
    supabase.from('pause_sessions').select('id,pause_type,started_at,ended_at').eq('agent_id',id).order('started_at',{ascending:false}).limit(300),
    supabase.from('notes').select('id,body,created_at,clients(first_name,last_name)').eq('agent_id',id).order('created_at',{ascending:false}).limit(300),
    supabase.from('client_assignments').select('*',{count:'exact',head:true}).eq('agent_id',id).eq('status','active'),
  ])
  const calls=(callRows??[]) as unknown as Call[];const callbacks=(callbackRows??[]) as unknown as Callback[];const pauses=(pauseRows??[]) as Pause[];const notes=(noteRows??[]) as unknown as Note[]
  const successes=calls.filter(call=>call.call_results?.is_success).length;const sales=calls.filter(call=>call.call_results?.is_sale).length;const callSeconds=calls.reduce((sum,call)=>sum+call.duration_seconds,0);const pauseSeconds=pauses.reduce((sum,pause)=>sum+Math.max(0,Math.floor((new Date(pause.ended_at||Date.now()).getTime()-new Date(pause.started_at).getTime())/1000)),0)
  const user=agent.users as unknown as {full_name:string;email:string}|null
  return <div className="space-y-6"><div><Link href="/agents" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><ArrowLeft size={16}/>Retour aux agents</Link><h1 className="mt-3 text-2xl font-black">{user?.full_name||agent.code}</h1><p className="text-sm text-slate-500">{user?.email} · Code {agent.code}</p></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[['Appels',calls.length],['Réussis',successes],['Ventes',sales],['File active',queueCount??0],['Durée appels',formatSeconds(callSeconds)],['Temps pause',formatSeconds(pauseSeconds)]].map(([label,value])=><div key={String(label)} className="card p-4"><p className="text-[10px] font-bold uppercase text-slate-400">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</section>
  <section className="card overflow-x-auto"><div className="panel-title flex items-center gap-2"><PhoneCall size={15}/>Historique des appels</div><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50"><tr><th className="p-3">Date</th><th className="p-3">Client</th><th className="p-3">Campagne</th><th className="p-3">Résultat</th><th className="p-3">Durée</th><th className="p-3">Résumé</th></tr></thead><tbody>{calls.map(call=><tr key={call.id} className="border-t"><td className="p-3">{new Date(call.called_at).toLocaleString('fr-DZ')}</td><td className="p-3 font-bold">{call.clients?`${call.clients.first_name} ${call.clients.last_name}`:'—'}</td><td className="p-3">{call.campaigns?.name||'—'}</td><td className="p-3">{call.call_results?.label||'—'}</td><td className="p-3">{formatSeconds(call.duration_seconds)}</td><td className="max-w-xs p-3">{call.summary||'—'}</td></tr>)}{!calls.length&&<tr><td colSpan={6} className="p-8 text-center">Aucun appel.</td></tr>}</tbody></table></section>
  <div className="grid gap-4 xl:grid-cols-3"><section className="card"><div className="panel-title flex items-center gap-2"><CalendarClock size={15}/>Rappels</div><div className="max-h-96 divide-y overflow-y-auto">{callbacks.map(item=><div key={item.id} className="p-3"><p className="font-bold">{item.clients?`${item.clients.first_name} ${item.clients.last_name}`:'Client supprimé'}</p><p className="text-xs text-slate-500">{new Date(item.scheduled_for).toLocaleString('fr-DZ')} · {item.status}</p><p className="mt-1 text-xs">{item.note}</p></div>)}{!callbacks.length&&<p className="p-5 text-sm text-slate-500">Aucun rappel.</p>}</div></section><section className="card"><div className="panel-title flex items-center gap-2"><Coffee size={15}/>Pauses</div><div className="max-h-96 divide-y overflow-y-auto">{pauses.map(item=>{const seconds=Math.max(0,Math.floor((new Date(item.ended_at||Date.now()).getTime()-new Date(item.started_at).getTime())/1000));return <div key={item.id} className="p-3"><p className="font-bold">{item.pause_type==='coffee'?'Café':'Déjeuner'}</p><p className="text-xs text-slate-500">{new Date(item.started_at).toLocaleString('fr-DZ')}</p><p className="font-mono text-xs">{formatSeconds(seconds)}</p></div>})}{!pauses.length&&<p className="p-5 text-sm text-slate-500">Aucune pause.</p>}</div></section><section className="card"><div className="panel-title flex items-center gap-2"><StickyNote size={15}/>Notes</div><div className="max-h-96 divide-y overflow-y-auto">{notes.map(item=><div key={item.id} className="p-3"><p className="font-bold">{item.clients?`${item.clients.first_name} ${item.clients.last_name}`:'Client supprimé'}</p><p className="text-xs text-slate-500">{new Date(item.created_at).toLocaleString('fr-DZ')}</p><p className="mt-1 text-xs">{item.body}</p></div>)}{!notes.length&&<p className="p-5 text-sm text-slate-500">Aucune note.</p>}</div></section></div></div>
}
