import Link from 'next/link'
import { Activity, ArrowRight, Headphones, UsersRound } from 'lucide-react'
import { redirect } from 'next/navigation'
import { getCurrentRole } from '@/lib/admin-auth'
import { createClient } from '@/lib/supabase/server'
import { DashboardLiveRefresh } from '@/components/crm/dashboard-live-refresh'

export const dynamic='force-dynamic'
type AgentRow={id:string;code:string;active:boolean;last_seen_at:string|null;users:{full_name:string;email:string}|null;calls:{count:number}[];callbacks:{count:number}[];pause_sessions:{id:string;started_at:string;ended_at:string|null}[]}
export default async function AgentsPage(){
  const role=await getCurrentRole();if(role!=='admin'&&role!=='supervisor')redirect('/dashboard')
  const supabase=await createClient();const {data}=await supabase.from('agents').select('id,code,active,last_seen_at,users!inner(full_name,email,role),calls(count),callbacks(count),pause_sessions(id,started_at,ended_at)').eq('users.role','agent').order('code')
  const agents=(data??[]) as unknown as AgentRow[];const cutoff=Date.now()-120000
  return <div className="space-y-6"><DashboardLiveRefresh/><div><h1 className="text-2xl font-black">Agents</h1><p className="mt-1 text-sm text-slate-500">Équipe visible selon vos autorisations Supabase.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{agents.map(agent=>{const online=agent.active&&Boolean(agent.last_seen_at)&&new Date(agent.last_seen_at!).getTime()>=cutoff;const paused=agent.pause_sessions.some(pause=>!pause.ended_at);return <Link key={agent.id} href={`/agents/${agent.id}`} className="card group p-5 transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-full bg-slate-800 font-black text-white">{(agent.users?.full_name||agent.code).slice(0,2).toUpperCase()}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${paused?'bg-orange-100 text-orange-700':online?'bg-emerald-100 text-emerald-700':!agent.active?'bg-red-100 text-red-700':'bg-slate-100 text-slate-500'}`}>{paused?'En pause':online?'En ligne':!agent.active?'Désactivé':'Hors ligne'}</span></div><h2 className="mt-4 font-black text-slate-700">{agent.users?.full_name||agent.code}</h2><p className="text-xs text-slate-500">{agent.users?.email} · {agent.code}</p><div className="mt-4 grid grid-cols-2 gap-2 text-center"><div className="rounded-lg bg-slate-50 p-2"><p className="font-black">{agent.calls?.[0]?.count??0}</p><p className="text-[10px] text-slate-500">Appels</p></div><div className="rounded-lg bg-slate-50 p-2"><p className="font-black">{agent.callbacks?.[0]?.count??0}</p><p className="text-[10px] text-slate-500">Rappels</p></div></div><div className="mt-4 flex items-center justify-end gap-2 text-xs font-bold text-emerald-700">Historique détaillé <ArrowRight size={15} className="transition group-hover:translate-x-1"/></div></Link>})}{!agents.length&&<div className="card col-span-full p-10 text-center"><UsersRound className="mx-auto text-slate-300"/><p className="mt-3 text-sm text-slate-500">Aucun agent visible dans votre équipe.</p></div>}</div></div>
}
