import { createClient } from '@/lib/supabase/server'
import { getCurrentRole } from '@/lib/admin-auth'
import { PauseClock } from '@/components/crm/pause-clock'

export const dynamic='force-dynamic'
type PauseRow={id:string;pause_type:string;started_at:string;ended_at:string|null;agents:{code:string;users:{full_name:string}|null}|null}
function seconds(row:{started_at:string;ended_at:string|null}){return Math.max(0,Math.floor((new Date(row.ended_at||Date.now()).getTime()-new Date(row.started_at).getTime())/1000))}
function format(total:number){const h=Math.floor(total/3600);const m=Math.floor(total%3600/60);const s=total%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
export default async function Pauses(){const role=await getCurrentRole();const supabase=await createClient();const {data:auth}=await supabase.auth.getUser();const {data:agent}=auth.user?await supabase.from('agents').select('id').eq('user_id',auth.user.id).maybeSingle():{data:null};const today=new Date();today.setHours(0,0,0,0);const {data:own}=agent?await supabase.from('pause_sessions').select('id,pause_type,started_at,ended_at').eq('agent_id',agent.id).gte('started_at',today.toISOString()).order('started_at',{ascending:false}):{data:[]};const ownRows=own??[];const open=ownRows.find(row=>!row.ended_at)??null;const ownTotal=ownRows.reduce((total,row)=>total+seconds(row),0);let all:PauseRow[]=[];if(role==='admin'||role==='supervisor'){const result=await supabase.from('pause_sessions').select('id,pause_type,started_at,ended_at,agents(code,users(full_name))').order('started_at',{ascending:false}).limit(500);all=(result.data??[]) as unknown as PauseRow[]}return <div className="space-y-6"><div><h1 className="text-xl font-black">Pauses</h1><p className="text-sm text-slate-500">Chronométrage réel des pauses café et déjeuner.</p></div>{role==='agent'&&<><div className="card p-4"><p className="text-xs uppercase text-slate-400">Temps de pause aujourd’hui</p><p className="mt-2 font-mono text-3xl font-black">{format(ownTotal)}</p></div><PauseClock open={open}/></>}{(role==='admin'||role==='supervisor')&&<section className="card overflow-x-auto"><div className="panel-title">Historique des pauses des agents</div><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 uppercase text-slate-500"><tr><th className="p-3">Agent</th><th className="p-3">Type</th><th className="p-3">Début</th><th className="p-3">Fin</th><th className="p-3">Durée</th></tr></thead><tbody className="divide-y divide-slate-100">{all.map(row=><tr key={row.id}><td className="p-3 font-bold">{row.agents?.users?.full_name||row.agents?.code||'—'}</td><td className="p-3">{row.pause_type==='coffee'?'Café':'Déjeuner'}</td><td className="p-3">{new Date(row.started_at).toLocaleString('fr-DZ')}</td><td className="p-3">{row.ended_at?new Date(row.ended_at).toLocaleString('fr-DZ'):'En cours'}</td><td className="p-3 font-mono">{format(seconds(row))}</td></tr>)}{!all.length&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">Aucune pause enregistrée.</td></tr>}</tbody></table></section>}</div>}
