'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ChevronLeft, ChevronRight, Clock, X } from 'lucide-react'
import { CallbackActions } from '@/components/crm/callback-actions'

export type CalendarCallback={id:string;scheduledFor:string;note:string;clientId:string|null;clientName:string;agentName:string}
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()
export function CallbackCalendar({callbacks,isAgent}:{callbacks:CalendarCallback[];isAgent:boolean}){
  const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)})
  const [selected,setSelected]=useState<CalendarCallback|null>(null)
  const days=useMemo(()=>{const start=new Date(month);const offset=(start.getDay()+6)%7;start.setDate(start.getDate()-offset);return Array.from({length:42},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return day})},[month])
  const formatter=new Intl.DateTimeFormat('fr-DZ',{month:'long',year:'numeric'})
  return <><section className="card overflow-hidden"><div className="flex items-center justify-between border-b bg-[#25292d] p-4 text-white"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="rounded p-2 hover:bg-white/10"><ChevronLeft/></button><h2 className="text-lg font-black capitalize">{formatter.format(month)}</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} className="rounded p-2 hover:bg-white/10"><ChevronRight/></button></div><div className="grid grid-cols-7 bg-slate-100 text-center text-[10px] font-black uppercase text-slate-500">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(day=><div key={day} className="p-2">{day}</div>)}</div><div className="grid grid-cols-7">{days.map(day=>{const events=callbacks.filter(item=>sameDay(new Date(item.scheduledFor),day));const today=sameDay(day,new Date());return <div key={day.toISOString()} className={`min-h-28 border-b border-r p-1.5 ${day.getMonth()!==month.getMonth()?'bg-slate-50 text-slate-300':'bg-white'}`}><div className={`mb-1 grid h-6 w-6 place-items-center rounded-full text-xs ${today?'bg-emerald-600 font-black text-white':''}`}>{day.getDate()}</div><div className="space-y-1">{events.slice(0,3).map(event=><button key={event.id} onClick={()=>setSelected(event)} className="block w-full truncate rounded bg-amber-100 px-1.5 py-1 text-left text-[10px] font-bold text-amber-800"><Clock size={9} className="mr-1 inline"/>{new Date(event.scheduledFor).toLocaleTimeString('fr-DZ',{hour:'2-digit',minute:'2-digit'})} {event.clientName}</button>)}{events.length>3&&<p className="text-[10px] font-bold text-slate-500">+{events.length-3} autre(s)</p>}</div></div>})}</div></section>{selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="card w-full max-w-md p-6"><div className="flex items-center justify-between"><h3 className="text-lg font-black">Rappel</h3><button onClick={()=>setSelected(null)}><X/></button></div><p className="mt-4 text-xl font-black">{selected.clientName}</p><p className="mt-2 text-sm text-slate-500">{new Date(selected.scheduledFor).toLocaleString('fr-DZ',{dateStyle:'full',timeStyle:'short'})}</p><p className="mt-1 text-sm text-slate-500">Agent : {selected.agentName}</p>{selected.note&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{selected.note}</p>}<div className="mt-5 flex flex-wrap gap-2">{selected.clientId&&<Link href={isAgent?'/work':`/clients/${selected.clientId}`} className="btn btn-primary">{isAgent?'Ouvrir le poste':'Ouvrir la fiche'}</Link>}<CallbackActions id={selected.id}/></div></div></div>}</>
}
