'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Coffee, Utensils } from 'lucide-react'
import { useRouter } from 'next/navigation'

export type LivePause={id:string;agentId:string;agentName:string;agentCode:string;pauseType:string;startedAt:string;endedAt:string|null}
const duration=(started:string,ended:string|null,now:number)=>{const total=Math.max(0,Math.floor((new Date(ended||now).getTime()-new Date(started).getTime())/1000));return `${String(Math.floor(total/3600)).padStart(2,'0')}:${String(Math.floor(total%3600/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
export function LivePauseMonitor({rows}:{rows:LivePause[]}){
  const [now,setNow]=useState(Date.now());const router=useRouter();useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);const refresh=window.setInterval(()=>router.refresh(),30000);return()=>{clearInterval(timer);clearInterval(refresh)}},[router])
  const active=rows.filter(row=>!row.endedAt);const history=rows.filter(row=>row.endedAt)
  return <div className="space-y-5"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-black">Pauses en cours</h2><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">{active.length} en pause</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{active.map(row=><Link href={`/agents/${row.agentId}`} key={row.id} className="card border-l-4 border-l-orange-500 p-5"><div className="flex items-center gap-3">{row.pauseType==='coffee'?<Coffee className="text-amber-600"/>:<Utensils className="text-emerald-600"/>}<div><p className="font-black">{row.agentName}</p><p className="text-xs text-slate-500">{row.pauseType==='coffee'?'Pause café':'Pause déjeuner'} · {row.agentCode}</p></div></div><p className="mt-4 font-mono text-3xl font-black text-slate-700">{duration(row.startedAt,null,now)}</p><p className="mt-1 text-xs text-slate-400">Depuis {new Date(row.startedAt).toLocaleTimeString('fr-DZ')}</p></Link>)}{!active.length&&<div className="card col-span-full p-8 text-center text-sm text-slate-500">Aucun agent en pause actuellement.</div>}</div></section><section className="card overflow-x-auto"><div className="panel-title">Historique des pauses</div><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 uppercase text-slate-500"><tr><th className="p-3">Agent</th><th className="p-3">Type</th><th className="p-3">Début</th><th className="p-3">Fin</th><th className="p-3">Durée</th></tr></thead><tbody>{history.map(row=><tr key={row.id} className="border-t"><td className="p-3 font-bold"><Link href={`/agents/${row.agentId}`}>{row.agentName}</Link></td><td className="p-3">{row.pauseType==='coffee'?'Café':'Déjeuner'}</td><td className="p-3">{new Date(row.startedAt).toLocaleString('fr-DZ')}</td><td className="p-3">{new Date(row.endedAt!).toLocaleString('fr-DZ')}</td><td className="p-3 font-mono">{duration(row.startedAt,row.endedAt,now)}</td></tr>)}{!history.length&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">Aucun historique.</td></tr>}</tbody></table></section></div>
}
